dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "pedroamador-github"
    token:
      secure: "mhg+p0yaha44kLOAMCplDzXInO0oeofFIBVyIyMm5+McRDuONrzPyB5pEfbHA7KvPngvWTiKJb3GbyVZRcepBGBJRd4sCZGFF16XjO1V1NQw1McAfMolpI1Fam5iBAAY2ndY0lMAlKxKvxez+MLvqQDjcADFbZsgiFJi/+fUehgGV1YB/D55yv+ZVBeVC892FEFtuUNufgUoKUvWlCV3/5623aulcaEjwWaKrqjphEuxpIddAku+dYPYAVUxH7usi1EdZLKCdbHIwIWE8wdaTz4y7Jc81tkWoMjJyiiB0DnYThZbQ4nZU6QLlyTSiKf7O5jJu3K0DKH/JryytfT07eFNiK9lG41BE5a/SGSvJSZYGm3iM6RR3iYsRshwaMdjql1A4U4L4fIef4hqGXumZKf/6BxSWNnG1eHUXgczNkoBlSVeeUSuPBaROKT/c6C9dxkx52WWorvn128dALfR/+/QD542A2/4Zg8NqGUEuvzJC+aJaEbGoBgN1rJJ1+eZH/kDs4lZlRe/bP9g8V/ZovCsMaa0KLSWnQRvPgWq1cLD/2Gmvi/5CFqWo1o0pM4yNnEKyu+0fA/ODQ2HYNGf5pJQU4ddDIFvBgkXzqbSsmQVi6dBepvIpiCtxtma1Fmyox9KxWiGG1cEtVTjvvnnqnz1C7rJh20LC56qvClEevM="
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
